name: Publish apispec

on:
  workflow_call:
    secrets:
      NPM_AUTH_TOKEN:
        required: true
      DOCKER_REGISTRY_USER:
        required: true
      DOCKER_REGISTRY_PASSWORD:
        required: true
    inputs:
      only_verify:
        required: false
        type: boolean
        default: false

jobs:
  apispec:
    name: Publish apispec
    runs-on: [self-hosted, common]
    container:
      image: gcr.io/ftcs-production/node-build-tools:16.13
      credentials:
        username: ${{ secrets.DOCKER_REGISTRY_USER }}
        password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Prepare dependencies
        run: |
          echo ${{ secrets.NPM_AUTH_TOKEN }} > /root/.npmrc
          npm i --quiet @general/apispec-manager

      - name: Verify publishing
        run: |
          ./node_modules/.bin/apispecman publish --token ${{ secrets.NPM_AUTH_TOKEN }} --dry-run

      - name: Publish apispec
        run: |
          ./node_modules/.bin/apispecman publish --token ${{ secrets.NPM_AUTH_TOKEN }}
        if: ${{ ! inputs.only_verify }}
