name: Lint

on:
  workflow_call:
    inputs:
      image:
        type: string
        required: false
        default: europe-docker.pkg.dev/ftcs-production/infrastructure/node-build-tools:16
    secrets:
      DOCKER_REGISTRY_USER:
        required: true
      DOCKER_REGISTRY_PASSWORD:
        required: true

jobs:
  lint:
    name: Lint
    runs-on: [self-hosted, common]
    container:
      image: ${{ inputs.image }}
      credentials:
        username: ${{ secrets.DOCKER_REGISTRY_USER }}
        password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: 'Workaround permissions issue'
        run: chown $(whoami):$(whoami) -R .

      - name: Install NPM dependencies
        run: npm ci

      - name: Run lint
        run: npm run lint:ci
