name: Verify

on:
  workflow_call:

jobs:
  lint:
    name: Lint
    runs-on: [self-hosted, common]
    container:
      image: gcr.io/ftcs-production/node-build-tools:14.19
      credentials:
        username: _json_key
        password: ${{  secrets.IMAGE_REGISTRY_SECRET }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Cache node_modules or install
        run: npm ci

      - name: Run lint
        run: npm run lint:ci
