name: Verify

on:
  workflow_call:

jobs:
  lint:
    name: Lint
    runs-on: [self-hosted, common]
    container: node:16.13-alpine
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Cache node_modules or install
        run: npm ci

      - name: Run lint
        run: npm run lint:ci
